package com.zuqi.ai.synthetic.dto;

import java.time.LocalDate;
import java.util.UUID;

/**
 * In-memory representation of a synthetic daily cash flow snapshot.
 *
 * Used to train the cash flow prediction model (Model #12).
 * Generated by {@link com.zuqi.ai.synthetic.generators.SyntheticCashFlowGenerator}.
 *
 * @param snapshotId                 Unique id
 * @param distributorRef             References a synthetic distributor bucket
 * @param date                       The calendar day this snapshot represents
 * @param totalInflow                KES received on this day (payments collected)
 * @param totalOutflow               KES paid out (supplier payments + expenses)
 * @param netCashFlow                totalInflow - totalOutflow
 * @param pendingOrdersValue         Open orders not yet invoiced at day start
 * @param overdueReceivablesTotal    Outstanding receivables > 30 days at day start
 * @param paymentDueNext7d           Receivables due in next 7 days from this date
 * @param avgDailyCollections7d      Rolling 7-day avg collections prior to this date
 * @param avgDailyCollections30d     Rolling 30-day avg collections prior to this date
 * @param collectionTrend            collections7d - collections30d (positive = improving)
 * @param pendingPurchaseOrdersValue Uncommitted PO spend at day start
 * @param avgDailyExpenses30d        Rolling 30-day avg expense outflows
 * @param upcomingSupplierPayments   Supplier invoices due in next 7 days
 * @param isPaydayWeek               true if week contains day 25–30 of month
 * @param isMonthEnd                 true if day >= 25
 * @param netCashFlow7dAgo           Actual net cash flow 7 days before this date
 * @param netCashFlow30dAgo          Actual net cash flow 30 days before this date
 */
public record SyntheticCashFlowSnapshot(
        UUID syntheticId,
        UUID distributorRef,
        LocalDate date,
        double totalInflow,
        double totalOutflow,
        double netCashFlow,
        double pendingOrdersValue,
        double overdueReceivablesTotal,
        double paymentDueNext7d,
        double avgDailyCollections7d,
        double avgDailyCollections30d,
        double collectionTrend,
        double pendingPurchaseOrdersValue,
        double avgDailyExpenses30d,
        double upcomingSupplierPayments,
        boolean isPaydayWeek,
        boolean isMonthEnd,
        double netCashFlow7dAgo,
        double netCashFlow30dAgo
) {}
