package com.zuqi.ai.synthetic.dto;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.UUID;

/**
 * In-memory representation of a synthetic bank statement line.
 *
 * Used to train the bank reconciliation classifier (Model #11).
 * Generated by {@link com.zuqi.ai.synthetic.generators.SyntheticBankStatementGenerator}.
 *
 * @param lineId             Unique id for this statement line
 * @param paymentRef         References {@link SyntheticPayment#syntheticId()} when this
 *                           is a matching line, or null for random unmatched lines
 * @param merchantRef        References {@link SyntheticMerchant#syntheticId()} when known
 * @param amount             Amount on bank statement (may differ slightly from payment)
 * @param statementDate      Date the transaction appeared on the statement
 * @param description        Narrative text (e.g. trading name, not system name)
 * @param reference          Reference number (may be truncated or missing)
 * @param paymentMethod      Inferred: MPESA, BANK_TRANSFER, CASH_DEPOSIT
 * @param isMatchingLine     true when a matching synthetic payment exists
 * @param trueMatchPaymentId id of the matched SyntheticPayment (null for unmatched)
 */
public record SyntheticBankStatementLine(
        UUID syntheticId,
        UUID paymentRef,
        UUID merchantRef,
        BigDecimal amount,
        LocalDate statementDate,
        String description,
        String reference,
        String paymentMethod,
        boolean isMatchingLine,
        UUID trueMatchPaymentId
) {}
