package com.zuqi.domain.ai;

import com.zuqi.domain.customer.Customer;
import com.zuqi.domain.distributor.Distributor;
import com.zuqi.domain.product.Product;
import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Product recommendation entity.
 * Records next-best-product suggestions generated by the collaborative
 * filtering / content-based ML model for a given customer.
 * Multiple recommendations per customer-product are allowed (timestamped).
 *
 * Table: ai_product_recommendations
 */
@Entity
@Table(name = "ai_product_recommendations", indexes = {
        @Index(name = "idx_product_rec_distributor_customer", columnList = "distributor_id, customer_id"),
        @Index(name = "idx_product_rec_customer", columnList = "customer_id"),
        @Index(name = "idx_product_rec_product", columnList = "product_id")
})
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductRecommendation {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "distributor_id", nullable = false)
    private Distributor distributor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Product product;

    @Column(name = "recommendation_score")
    private Double recommendationScore;

    @Column(name = "reason", columnDefinition = "TEXT")
    private String reason;

    @Column(name = "source", length = 50)
    private String source;

    @Column(name = "data_phase", length = 20)
    private String dataPhase;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
