package com.zuqi.domain.ai;

public enum RecommendationType {
    SALES_TREND,
    INVENTORY_OPTIMIZATION,
    PAYMENT_COLLECTION,
    REP_PERFORMANCE,
    MERCHANT_ENGAGEMENT,
    DELIVERY_EFFICIENCY,
    CREDIT_MANAGEMENT,
    PRICING_STRATEGY,
    ROUTE_OPTIMIZATION,
    COST_REDUCTION,
    REVENUE_OPPORTUNITY
}
