-- AI Operational Recommendations
-- Stores recommendations generated by the AI agent for operational improvements
-- Part of Phase 6: AI Agent Module

CREATE TABLE IF NOT EXISTS ai_recommendations (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    distributor_id  UUID NOT NULL,
    recommendation_type VARCHAR(50) NOT NULL,
    observation     TEXT NOT NULL,
    evidence        JSONB NOT NULL,
    recommendation  TEXT NOT NULL,
    expected_impact TEXT,
    priority        VARCHAR(20) NOT NULL,
    status          VARCHAR(20) DEFAULT 'PENDING',
    acted_on_at     TIMESTAMP,
    outcome         TEXT,
    model_version   VARCHAR(50),
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_recommendations_distributor FOREIGN KEY (distributor_id)
        REFERENCES distributors(id) ON DELETE CASCADE,
    CONSTRAINT chk_recommendation_type CHECK (recommendation_type IN (
        'sales_trend', 'inventory_optimization', 'payment_collection',
        'rep_performance', 'merchant_engagement', 'delivery_efficiency',
        'credit_management', 'pricing_strategy', 'route_optimization',
        'cost_reduction', 'revenue_opportunity'
    )),
    CONSTRAINT chk_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED'))
);

-- Comments for documentation
COMMENT ON TABLE ai_recommendations IS 'AI agent-generated operational recommendations with outcome tracking';
COMMENT ON COLUMN ai_recommendations.observation IS 'What the agent observed: "Sales in Westlands dropped 18% over 3 weeks"';
COMMENT ON COLUMN ai_recommendations.evidence IS 'JSON: Supporting data points that led to this recommendation';
COMMENT ON COLUMN ai_recommendations.recommendation IS 'Specific action to take: "Increase sales rep visits to top 5 merchants"';
COMMENT ON COLUMN ai_recommendations.expected_impact IS 'Projected outcome if recommendation followed';
COMMENT ON COLUMN ai_recommendations.status IS 'Workflow: PENDING -> ACCEPTED/REJECTED -> COMPLETED';
COMMENT ON COLUMN ai_recommendations.outcome IS 'Actual result after implementing recommendation (for learning)';
COMMENT ON COLUMN ai_recommendations.model_version IS 'AI agent version that generated this recommendation';

-- Indexes for recommendation management
CREATE INDEX IF NOT EXISTS idx_recommendations_distributor
    ON ai_recommendations(distributor_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_recommendations_status
    ON ai_recommendations(status, priority DESC);

CREATE INDEX IF NOT EXISTS idx_recommendations_priority
    ON ai_recommendations(priority, status);

CREATE INDEX IF NOT EXISTS idx_recommendations_type
    ON ai_recommendations(recommendation_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_recommendations_created
    ON ai_recommendations(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_recommendations_pending
    ON ai_recommendations(distributor_id, priority DESC, created_at DESC) WHERE status = 'PENDING';
