-- AI Delivery Routes
-- Optimized delivery routes generated by Timefold Solver and GraphHopper
-- Part of Phase 5: Route Optimization Module

CREATE TABLE IF NOT EXISTS ai_delivery_routes (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    distributor_id  UUID NOT NULL,
    route_date      DATE NOT NULL,
    vehicle_id      UUID,
    vehicle_info    JSONB,
    driver_id       UUID NOT NULL,
    stop_sequence   JSONB NOT NULL,
    total_distance_km   DOUBLE PRECISION,
    total_duration_min  DOUBLE PRECISION,
    load_utilization_pct DOUBLE PRECISION,
    solver_time_ms      INTEGER,
    status          VARCHAR(20) DEFAULT 'PLANNED',
    actual_distance_km  DOUBLE PRECISION,
    actual_duration_min DOUBLE PRECISION,
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_delivery_routes_distributor FOREIGN KEY (distributor_id)
        REFERENCES distributors(id) ON DELETE CASCADE,
    CONSTRAINT fk_delivery_routes_driver FOREIGN KEY (driver_id)
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_route_status CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

-- Comments for documentation
COMMENT ON TABLE ai_delivery_routes IS 'AI-optimized delivery routes generated by Timefold Solver with GraphHopper road network data';
COMMENT ON COLUMN ai_delivery_routes.vehicle_id IS 'Vehicle info stored in metadata for now (vehicles table TBD)';
COMMENT ON COLUMN ai_delivery_routes.vehicle_info IS 'JSON: {capacity_kg, capacity_volume, registration, type}';
COMMENT ON COLUMN ai_delivery_routes.stop_sequence IS 'Ordered list of {merchant_id, eta, order_ids}';
COMMENT ON COLUMN ai_delivery_routes.status IS 'Workflow: PLANNED -> IN_PROGRESS -> COMPLETED/CANCELLED';
COMMENT ON COLUMN ai_delivery_routes.actual_distance_km IS 'Filled after completion (for model improvement)';

-- Indexes for route management
CREATE INDEX IF NOT EXISTS idx_delivery_routes_distributor
    ON ai_delivery_routes(distributor_id);

CREATE INDEX IF NOT EXISTS idx_delivery_routes_date
    ON ai_delivery_routes(route_date);

CREATE INDEX IF NOT EXISTS idx_delivery_routes_driver
    ON ai_delivery_routes(driver_id);

CREATE INDEX IF NOT EXISTS idx_delivery_routes_status
    ON ai_delivery_routes(status);

CREATE INDEX IF NOT EXISTS idx_delivery_routes_created
    ON ai_delivery_routes(created_at DESC);
