-- AI Delivery Routes
-- Optimized delivery routes generated by Timefold Solver and GraphHopper
-- Consumed by route assignment and delivery operations
-- Part of Phase 5: Route Optimization Module

CREATE TABLE IF NOT EXISTS ai_delivery_routes (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    distributor_id  UUID NOT NULL,
    sales_rep_id    UUID NOT NULL,
    route_date      DATE NOT NULL,
    merchant_order  JSONB NOT NULL,
    total_distance_km DOUBLE PRECISION NOT NULL,
    total_duration_min INTEGER NOT NULL,
    total_orders    INTEGER NOT NULL,
    optimization_score DOUBLE PRECISION,
    route_geometry  TEXT,
    status          VARCHAR(20) DEFAULT 'PLANNED',
    assigned_at     TIMESTAMP,
    started_at      TIMESTAMP,
    completed_at    TIMESTAMP,
    actual_distance_km DOUBLE PRECISION,
    actual_duration_min INTEGER,
    model_version   VARCHAR(50),
    created_at      TIMESTAMP DEFAULT NOW(),
    updated_at      TIMESTAMP DEFAULT NOW(),
    CONSTRAINT fk_delivery_routes_distributor FOREIGN KEY (distributor_id)
        REFERENCES distributors(id) ON DELETE CASCADE,
    CONSTRAINT fk_delivery_routes_sales_rep FOREIGN KEY (sales_rep_id)
        REFERENCES sales_reps(id) ON DELETE CASCADE,
    CONSTRAINT uq_delivery_route UNIQUE(sales_rep_id, route_date),
    CONSTRAINT chk_route_status CHECK (status IN ('PLANNED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

-- Comments for documentation
COMMENT ON TABLE ai_delivery_routes IS 'AI-optimized delivery routes generated by Timefold Solver with GraphHopper road network data';
COMMENT ON COLUMN ai_delivery_routes.merchant_order IS 'JSON: Ordered list of merchant IDs and coordinates [{merchant_id, lat, lon, eta, sequence}]';
COMMENT ON COLUMN ai_delivery_routes.total_distance_km IS 'Total route distance optimized by GraphHopper';
COMMENT ON COLUMN ai_delivery_routes.total_duration_min IS 'Estimated total duration including drive time and stop time';
COMMENT ON COLUMN ai_delivery_routes.optimization_score IS 'Quality score from Timefold Solver (0-1, higher = better)';
COMMENT ON COLUMN ai_delivery_routes.route_geometry IS 'GeoJSON LineString or WKT for map visualization';
COMMENT ON COLUMN ai_delivery_routes.status IS 'Workflow: PLANNED -> ASSIGNED -> IN_PROGRESS -> COMPLETED/CANCELLED';
COMMENT ON COLUMN ai_delivery_routes.actual_distance_km IS 'Actual distance traveled (for model improvement)';
COMMENT ON CONSTRAINT uq_delivery_route ON ai_delivery_routes IS 'One optimized route per sales rep per day';

-- Indexes for route management
CREATE INDEX IF NOT EXISTS idx_delivery_routes_distributor
    ON ai_delivery_routes(distributor_id, route_date DESC);

CREATE INDEX IF NOT EXISTS idx_delivery_routes_sales_rep
    ON ai_delivery_routes(sales_rep_id, route_date DESC);

CREATE INDEX IF NOT EXISTS idx_delivery_routes_status
    ON ai_delivery_routes(status, route_date DESC);

CREATE INDEX IF NOT EXISTS idx_delivery_routes_date
    ON ai_delivery_routes(route_date DESC);

CREATE INDEX IF NOT EXISTS idx_delivery_routes_planned
    ON ai_delivery_routes(distributor_id, status, route_date) WHERE status = 'PLANNED';

CREATE INDEX IF NOT EXISTS idx_delivery_routes_in_progress
    ON ai_delivery_routes(sales_rep_id, route_date) WHERE status = 'IN_PROGRESS';
